# Generated by Django 2.0 on 2017-12-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.TextField(blank=True, null=True, unique=True)),
                ('num_rating', models.IntegerField(blank=True, null=True)),
                ('av_score', models.FloatField(blank=True, null=True)),
                ('var_score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratingid', models.IntegerField(blank=True, null=True)),
                ('productid', models.TextField(blank=True, null=True)),
                ('userid', models.TextField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ratings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.TextField(blank=True, null=True, unique=True)),
                ('num_rating', models.IntegerField(blank=True, null=True)),
                ('av_score', models.FloatField(blank=True, null=True)),
                ('var_score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
