# Generated by Django 2.0 on 2018-01-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0002_product_rating_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Util',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'utils',
                'managed': False,
            },
        ),
    ]
